// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI1zF-F1kafMfnArfKQFq24-_7ZEmlN2s',
    appId: '1:491483932831:web:f6b6c597871ea442dbdaaa',
    messagingSenderId: '491483932831',
    projectId: 'picder-photo-storing-app',
    authDomain: 'picder-photo-storing-app.firebaseapp.com',
    storageBucket: 'picder-photo-storing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoM42YXUyi5mTqiuhrpb1aMb9_63lOyzU',
    appId: '1:491483932831:android:5c76a81a2303b458dbdaaa',
    messagingSenderId: '491483932831',
    projectId: 'picder-photo-storing-app',
    storageBucket: 'picder-photo-storing-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUCUazvhliCFgXeHdUs42Qx8ZXFMiMxs',
    appId: '1:491483932831:ios:197cd287193df572dbdaaa',
    messagingSenderId: '491483932831',
    projectId: 'picder-photo-storing-app',
    storageBucket: 'picder-photo-storing-app.firebasestorage.app',
    iosBundleId: 'com.example.picder',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUCUazvhliCFgXeHdUs42Qx8ZXFMiMxs',
    appId: '1:491483932831:ios:197cd287193df572dbdaaa',
    messagingSenderId: '491483932831',
    projectId: 'picder-photo-storing-app',
    storageBucket: 'picder-photo-storing-app.firebasestorage.app',
    iosBundleId: 'com.example.picder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI1zF-F1kafMfnArfKQFq24-_7ZEmlN2s',
    appId: '1:491483932831:web:23223ee40638a247dbdaaa',
    messagingSenderId: '491483932831',
    projectId: 'picder-photo-storing-app',
    authDomain: 'picder-photo-storing-app.firebaseapp.com',
    storageBucket: 'picder-photo-storing-app.firebasestorage.app',
  );
}
